### PR TITLE
isolate the sudo-runnable command

### LINKED ISSUE #456: expecting an array or an iterable object but got [object Null]
https://github.com/resin-io/resin-cli/issues/452#issuecomment-288661711

My test account has passwordless sudo. When this code is ran
```
if os.platform() isnt 'win32'
  console.log('Type your computer password to continue')

return president.executeAsync(command)
```

it prints the message and then the control returns to the main program after a while.
During the `device init` the program then crashes with `expecting an array or an iterable object but got [object Null]` which I don't yet know where it's coming from.

Front logo [Front conversations](https://app.frontapp.com/open/top_1cbr)

### PR DESCRIPTION
**Pull request by emirotin**
This isolates the command that needs sudo (writing tot he actual physical disk) from the userland operations that require user authentication, like collecting the info from the API.

Also fixes the bluebird bug and updates a bunch of dependencies

Closes #456, #452

### CODE REVIEW

File: lib/actions/device.coffee [hunk 1]
```diff
@@ -392,27 +392,23 @@ exports.init =
...
-
-							helpers.sudo([ 'os', 'initialize', temporalPath, '--type', application.device_type ], message)
-
+						configureCommand = "os configure #{tempPath} #{device.uuid}"
+						if options.advanced
+							configureCommand += ' --advanced'
+						capitano.runAsync(configureCommand)
+						.then ->
+							osInitCommand = "os initialize #{tempPath} --type #{application.device_type}"
+							capitano.runAsync(osInitCommand)
```
Comment (pimterry) [inline lib/actions/device.coffee]: Nit: the intermediate variable here doesn't add anything, it just makes me think this is used elsewhere, but it doesn't seem to be...

File: lib/actions/device.coffee [hunk 2]
```diff
@@ -392,27 +392,23 @@ exports.init =
...
-							'''
-
-							helpers.sudo([ 'os', 'initialize', temporalPath, '--type', application.device_type ], message)
-
+						configureCommand = "os configure #{tempPath} #{device.uuid}"
+						if options.advanced
+							configureCommand += ' --advanced'
+						capitano.runAsync(configureCommand)
+						.then ->
+							osInitCommand = "os initialize #{tempPath} --type #{application.device_type}"
```
Comment (pimterry) [inline lib/actions/device.coffee]: Do we need quotes around `#{tempPath}`, here and above?

File: lib/actions/util.coffee [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+See the License for the specific language governing permissions and
+limitations under the License.
+###
+
+# These are internal commands we want to be runnable from the outside
+# One use-case for this is spawning the minimal operation with root priviledges
+
+exports.osInit =
+	signature: 'util osinit <image> <type> <config>'
```
Comment (pimterry) [inline lib/actions/util.coffee]: Could we use `internal` instead of `util`? Makes it clearer what's going on imo, both for cli users and in the code.

File: lib/utils/helpers.coffee [hunk 4]
```diff
@@ -47,17 +47,14 @@ exports.stateToString = (state) ->
...
-exports.sudo = (command, message) ->
-	command = _.union(_.take(process.argv, 2), command)
-	console.log(message)
-
+exports.sudo = (command) ->
 	if os.platform() isnt 'win32'
-		console.log('Type your computer password to continue')
+		console.log('If asked please type your computer password to continue')
 
+	command = _.union(_.take(process.argv, 2), command)
```
Comment (pimterry) [inline lib/utils/helpers.coffee]: I'm not sure why, but it looks like this worked before without this change, with similar arguments to what we're now using. What's changed?

File: lib/utils/helpers.coffee [hunk 5]
```diff
@@ -70,3 +67,21 @@ exports.getManifest = (image, deviceType) ->
...
+	step.on('stdout', _.bind(process.stdout.write, process.stdout))
+	step.on('stderr', _.bind(process.stderr.write, process.stderr))
+
+	step.on 'state', (state) ->
+		return if state.operation.command is 'burn'
+		console.log(exports.stateToString(state))
+
+	bar = new visuals.Progress('Writing Device OS')
+
+	step.on('burn', _.bind(bar.update, bar))
```
Comment (pimterry) [inline lib/utils/helpers.coffee]: Why don't we just use native `.bind`? (here and above)

File: lib/actions/device.coffee (hunk 2 above)
Comment (emirotin) [inline lib/actions/device.coffee]: It's a specially built temp path, very unlikely to have spaces. But can put of course

File: lib/actions/device.coffee (hunk 1 above)
Comment (emirotin) [inline lib/actions/device.coffee]: Nope, it's just to separate the things: first we build the command, then we use it. I prefer this style when the long strings manipulation is happening.

File: lib/utils/helpers.coffee (hunk 4 above)
Comment (emirotin) [inline lib/utils/helpers.coffee]: I have no idea how this used to work, really. 
It was sudo-ing the command that tries to fetch some data using the SDK. 
The change that I've done only sudo-es the command that writes to the drive given all the required info.

File: lib/utils/helpers.coffee (hunk 5 above)
Comment (emirotin) [inline lib/utils/helpers.coffee]: We can of course, I've just copied this verbatim. Had the same  thought, but didn't want to put more changes.
